/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Singleton;
import org.example.ComputerBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println();
        System.out.println("Singleton: ");
        System.out.println("Creating first instace with data 10");
        Singleton singleton = Singleton.get_instance();
        singleton.set_data(10);
        System.out.println("Creating second instace");
        Singleton singleton_2 = Singleton.get_instance();

        System.out.println("Are they aliases: " + (singleton == singleton_2));

        System.out.println("Computer using builder pattern\n");

        ComputerBuilder computer = new ComputerBuilder.Builder()
                                    .cpu("Intel")
                                    .gpu("5090")
                                    .ram("32GB")
                                    .storage("2TB")
                                    .build();
        
        System.out.println(computer);




        


    }
}
